### ISSUE TITLE
SMPL to SMPLX error

### ISSUE THREAD

**Issue by Alex-web100** [vchoutas/smplx#118]
Hello,
when trying to run the SMPL to SMPLX transfer, I encounter the following error
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sashawald/Documents/smplx/transfer_model/__main__.py", line 100, in <module>
    main()
  File "/home/sashawald/Documents/smplx/transfer_model/__main__.py", line 54, in main
    body_model = build_layer(model_path, **exp_cfg.body_model)
  File "/home/sashawald/Documents/smplx/smplx/body_models.py", line 2345, in build_layer
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type body, exiting!
```
Does anyone know what might be causing this issue? I am trying to convert a folder of .ply files. Thank you!

**Comment by Shreeshail-Hingane** [comment]
I am getting the same error. How did you solve it @Alex-web100 ?

**Comment by Alex-web100** [comment]
Hello! I don't have very detailed notes on how I fixed it, but I did write down that it ended up being an issue with the way the files on my machine were structured. I would recommend checking that your folder structure looks similar to the one outlined [here](https://github.com/vchoutas/smplx/tree/master/transfer_model), and also to ensure that you have the correct file path entered in the config file – for me it needed to be adjusted.

**Comment by Shreeshail-Hingane** [comment]
I see. I solved this problem by commenting out the following lines from the `build_layer()` function in `smplx/body_models.py`: 
```
else:
    model_type = osp.basename(model_path).split('_')[0].lower()
```
because it was incorrectly changing the value of variable `model_type` to `'body'`, whereas the original value of `model_type` passed to the `build_layer()` function was correctly set (to either of `'smpl/smplh/smplx'`)

**Comment by Shreeshail-Hingane** [comment]
@Alex-web100 Thanks for the prompt reply. The stuff you mentioned about the setting the directory structure right: I found it useful to resolve the following error that I encountered: 
`ImportError: attempted relative import with no known parent package`

**Comment by leejielong** [comment]
Hi, just wanted to provide the correct solution to this issue. This error happens if we do not create the `body_models` folder under `transfer_data`. So the solution is to simply create the `transfer_data/body_models` folder.

**Comment by soddday** [comment]
> Hi, just wanted to provide the correct solution to this issue. This error happens if we do not create the `body_models` folder under `transfer_data`. So the solution is to simply create the `transfer_data/body_models` folder.

Hi @leejielong When I transfer SMPLX to SMPLH I create the folder but still meet the same error
`PS E:\smplx2smplh\smplx\transfer_model> python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\smplx2smplh\smplx\transfer_model\transfer_model.py", line 26, in <module>
    from .utils import get_vertices_per_edge
ImportError: attempted relative import with no known parent package`

I run it in the path smplx\transfer_model as below

<img width="1204" height="175" alt="Image" src="https://github.com/user-attachments/assets/25137686-a62a-46d4-aef6-db4664dadac2" />

<img width="502" height="616" alt="Image" src="https://github.com/user-attachments/assets/3997ffbc-77ba-48b6-9429-14ab83112465" />

Then I change the path I run `python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml`
but still meet errors.
`(.venv) PS E:\smplx2smplh\smplx> python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\smplx2smplh\smplx\transfer_model\__main__.py", line 30, in <module>
    from .config import parse_args
  File "E:\smplx2smplh\smplx\transfer_model\config\__init__.py", line 17, in <module>
    from .cmd_parser import parse_args
  File "E:\smplx2smplh\smplx\transfer_model\config\cmd_parser.py", line 27, in <module>
    from .defaults import conf as default_conf
  File "E:\smplx2smplh\smplx\transfer_model\config\defaults.py", line 24, in <module>
    from .dataset_defaults import conf as dataset_cfg, DatasetConfig
  File "E:\smplx2smplh\smplx\transfer_model\config\dataset_defaults.py", line 26, in <module>
    @dataclass
     ^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'transfer_model.config.dataset_defaults.MeshFolder'> for field mesh_folder is not allowed: use default_factory
(.venv) PS E:\smplx2smplh\smplx> `

can u tell me I should run `python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml` in which path and how to slove my problem?
