### ISSUE TITLE
Something wrong running vis_mano_vertices.py

### ISSUE THREAD

**Issue by shawnFuu** [vchoutas/smplx#195]
When I was running this command:python examples/vis_mano_vertices.py --model-folder  F:/project/SMPL-X/smplx-main/models --corr-fname ./correspondences/MANO_SMPLX_vertex_ids.pkl
I got this:
(E:\pycharm\env\DLenv0) F:\project\SMPL-X\smplx-main>python examples/vis_mano_vertices.py --model-folder  F:/project/SMPL-X/smplx-main/models --corr-fname ./correspondences/MANO_SMPLX_vertex_ids.pkl
Traceback (most recent call last):
  File "F:\project\SMPL-X\smplx-main\examples\vis_mano_vertices.py", line 96, in <module>
    main(model_folder, corr_fname, ext=ext,
  File "F:\project\SMPL-X\smplx-main\examples\vis_mano_vertices.py", line 47, in main
    output = model(betas=betas, expression=expression,
  File "E:\pycharm\env\DLenv0\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\pycharm\env\DLenv0\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\pycharm\env\DLenv0\lib\site-packages\smplx-0.1.28-py3.12.egg\smplx\body_models.py", line 1243, in forward
    vertices, joints = lbs(shape_components, full_pose, self.v_template,
  File "E:\pycharm\env\DLenv0\lib\site-packages\smplx-0.1.28-py3.12.egg\smplx\lbs.py", line 209, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "E:\pycharm\env\DLenv0\lib\site-packages\smplx-0.1.28-py3.12.egg\smplx\lbs.py", line 295, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "E:\pycharm\env\DLenv0\lib\site-packages\torch\functional.py", line 375, in einsum
    return einsum(equation, *_operands)
  File "E:\pycharm\env\DLenv0\lib\site-packages\torch\functional.py", line 380, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
**RuntimeError: einsum(): subscript l has size 26 for operand 1 which does not broadcast with previously seen size 20**

I donnot know what is happening. But running demo.py is alright. Can someone give me help?

**Comment by zjy-2020** [comment]
Hello, have you finally solved this problem？

**Comment by hejia-zhang** [comment]
Have you addressed this issue? I have the same problem.
