### ISSUE TITLE
Issue with body_models.py

### ISSUE THREAD

**Issue by vas0206** [vchoutas/smplx#210]
I am running into the error below when calling body_models.py. What is the issue?
```
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'
```

**Comment by meongeun** [comment]
I'm having the same issue. please let me know how you solve it.

**Comment by wangfusehng** [comment]
Me too

**Comment by pogopo789** [comment]
In the https://eth-ait.github.io/aitviewer/frontend.html, it tells us to follow the smplx data structure:

![Image](https://github.com/user-attachments/assets/d320605a-713a-42cb-ac83-867c6b9e57a8)

and in the smplx git the also shows us the structure

![Image](https://github.com/user-attachments/assets/c72dba4a-151e-424a-b7c4-ce0447ab3639)

But the smplh folder need to be merged with Mona file
so you need to follow this instruction for that https://github.com/vchoutas/smplx/blob/main/tools/README.md
Once you done, you will get the  SMPLH_FEMALE.pkl and SMPLH_MALE.pkl for the folder smplh. Which solve the problem

**Comment by soddday** [comment]
hi @pogopo789 
 when run python write_obj.py --model-folder ../models/ --motion-file ..\transfer_data\support_data\npz_data\00001_0.npz --output-folder ../transfer_data/meshes/amass_sample/ to process my own npz file(SMPL-X  NEUTRAL),I meet this error WARNING: You are using a SMPL+H model, with only 16 shape coefficients.
num_betas=1, shapedirs.shape=(6890, 3, 16), self.SHAPE_SPACE_DIM=300
Traceback (most recent call last):
File "E:\smplx2smplh\smplx\transfer_model\write_obj.py", line 199, in
main(
File "E:\smplx2smplh\smplx\transfer_model\write_obj.py", line 59, in main
model = smplx.create(
^^^^^^^^^^^^^
File "E:\smplx2smplh\smplx\transfer_model\smplx\body_models.py", line 2419, in create
return SMPLH(model_path, *kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\smplx2smplh\smplx\transfer_model\smplx\body_models.py", line 612, in init
left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Struct' object has no attribute 'hands_componentsl'
I already get all the pkl and npz files of SMPL

<img width="461" height="669" alt="Image" src="https://github.com/user-attachments/assets/ac01f354-78cf-4e38-8a4b-f9631ebfa81f" />

**Comment by soddday** [comment]
hi @vas0206 @pogopo789 @wangfusehng @meongeun did you slove this problem?
