### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by piyushapple1998** [vchoutas/smplx#32]
When I try to run the following code : 
python3 smplifyx/main.py --config cfg_files/fit_smplx.yaml --data_folder test_images --output_folder results --visualize="True" --model_folder models/smplx/SMPLX_NEUTRAL.npz --vposer_ckpt vposer --part_segm_fn smplx_parts_segm.pkl

Output:

Processing: test_images/images/01_img.jpg
Found Trained Model: vposer/snapshots/TR00_E096.pt
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/media/Simpl-x/smplify-x-master/smplifyx/fit_single_frame.py", line 274, in fit_single_frame
    focal_length=focal_length, dtype=dtype)
  File "/home/username/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/media/Simpl-x/smplify-x-master/smplifyx/fitting.py", line 89, in guess_init
    for edge in edge_idxs:
**TypeError: 'NoneType' object is not iterable**

I get this error. I have installed all the requirements and I have cuda installed. I tried to run this example with the test_images folder provided.
[test_images.zip](https://github.com/vchoutas/smplify-x/files/4868221/test_images.zip)

**Comment by piyushapple1998** [comment]
It will be a huge help if anyone would reply as I need to research further for my college project. I have it due in 2 days. I have cleaned and installed everything. It still shows me this error.

**Comment by piyushapple1998** [comment]
File "/media/Simpl-x/smplify-x-master/smplifyx/fitting.py", line 89, in guess_init
for edge in edge_idxs:
diff3d = []
diff2d = []
print(edge_idxs) #I added this code to see the output and it shows none on the console.**
for edge in edge_idxs:
diff3d.append(joints_3d[:, edge[0]] - joints_3d[:, edge[1]])
diff2d.append(joints_2d[:, edge[0]] - joints_2d[:, edge[1]])

**File "/media/Simpl-x/smplify-x-master/smplifyx/fit_single_frame.py", line 274, in fit_single_frame
focal_length=focal_length, dtype=dtype) Traced to the following code :
edge_indices = kwargs.get('body_tri_idxs')
print(edge_indices) #I added this code to see the output and it shows none on the console.
init_t = fitting.guess_init(body_model, gt_joints, edge_indices,
use_vposer=use_vposer, vposer=vposer,
pose_embedding=pose_embedding,
model_type=kwargs.get('model_type', 'smpl'),
focal_length=focal_length, dtype=dtype)
