### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'pretty' not in 'MeshFolder'

### ISSUE THREAD

**Issue by woo1** [vchoutas/smplx#74]
Thanks for sharing the code.
When I run "python -m transfer_model --exp-cfg config_files/smpl2smplx.yaml", this error raises

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Projects/smplx/transfer_model/__main__.py", line 101, in <module>
    main()
  File "/Projects/smplx/transfer_model/__main__.py", line 73, in main
    data_obj_dict = build_dataloader(exp_cfg)
  File "/Projects/smplx/transfer_model/data/build.py", line 31, in build_dataloader
    logger.info(mesh_folder_cfg.pretty())
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 167, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/Projects/smplx/venv/lib/python3.7/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'pretty' not in 'MeshFolder'
    full_key: datasets.mesh_folder.pretty
    reference_type=MeshFolder
    object_type=MeshFolder

**Comment by yth223** [comment]
I'm having the same problem.
It seems to be a workaround by adding a slightly older library.
pip install omegaconf==2.0.0
