### ISSUE TITLE
Convert SMPL-X to SMPL

### ISSUE THREAD

**Issue by Tonight1121** [vchoutas/smplx#81]
Hi thanks for the code! I tried to convert an SMPL-x model (.obj generated by blender add-on) to a SMPL representation. While trying to run this code `python main.py --exp-cfg config_files/smplx2smpl.yaml`, I met several problems.

1. I could not find the main.py scripts inside the project. Does it actually mean the __main__.py under transfer_model folder? If so, is there any specific reasons for naming it that way?

2. I am not sure under which folder to run this command. Specifically, if I ran this command under the root smplx folder, then it should be `python transfer_model/__main__.py`; if ran under the transfer_model directory, the config_files is actually in its parent directory and the path cannot be found using `config_files/smplx2smpl.yaml`.

3. Basically the similar problem as in 2, since I am not sure about where to run the command, there are many relative imports that cannot work, and continuously produces this error 
> ImportError: attempted relative import with no known parent package

Thank you for taking time to solve our problems in advance!

Best

**Comment by Tonight1121** [comment]
I tried to make one sample case working by starting with the sample configuration in `smplx2smpl.yaml`. By converting SMPL-X to SMPL, specifically, how should we specify the source model .obj and the output directory? I see [here](https://github.com/vchoutas/smplx/blob/77cf2a7010370c1e44141fab5d15ad8a0841bc9d/smplx/body_models.py#L2334) the building_layer function is trying to get the model type out of a path string. By using the default setting I got `model_path=transfer_data/body_models`, since in `smplx2smpl.yaml`, the folder of body_model is specified as `transfer_data/body_models`. By running the provided default sample setting, the model type was extracted to be "body" which does not belong to the SMPL family. 

> Traceback (most recent call last):
>   File "__main__.py", line 100, in <module>       
>     main()
>   File "__main__.py", line 54, in main
>     body_model = build_layer(model_path, **exp_cfg.body_model)
>   File "/home/hengtao/anaconda3/lib/python3.8/site-packages/smplx/body_models.py", line 2345, in build_layer
>     raise ValueError(f'Unknown model type {model_type}, exiting!')
> ValueError: Unknown model type body, exiting! 

I would really appreciate the help in my issues. It would be great if I can have one case running smoothly, then I can read along the codes to have a better understanding of this excellent work. Thank you so much for the time!

**Comment by kbrodt** [comment]
There is a typo in documentation for `SMPL-X to SMPL`. You should run `python -m transfer_model --exp-cfg config_files/smplx2smpl.yaml` (instead of `python main.py --exp-cfg config_files/smplx2smpl.yaml`) from root repository directory.

SMPL-X meshes must be in

```
transfer_data
├── meshes
│   ├── smpl
│   ├── smplx  # <-- HERE
│   ├──----- mesh1.obj
│   ├──----- mesh2.obj
│   ├──----- ...
├── smpl2smplh_def_transfer.pkl
├── smpl2smplx_deftrafo_setup.pkl
├── smplh2smpl_def_transfer.pkl
├── smplh2smplx_deftrafo_setup.pkl
├── smplx2smpl_deftrafo_setup.pkl
├── smplx2smplh_deftrafo_setup.pkl
├── smplx_mask_ids.npy
```

**Comment by sye8** [comment]
According to [`build_layer`](https://github.com/vchoutas/smplx/blob/77cf2a7010370c1e44141fab5d15ad8a0841bc9d/smplx/body_models.py#L2280), if `model_path` is not a directory (which includes the case of doesn't exist), will extract the first word separated by `_` as the model type. To avoid the error, either provide a path to the `.pkl` of the model, or provide the directory where the model is under

**Comment by gngdb** [comment]
I've managed to use this code (after making some edits in [my fork](https://github.com/gngdb/smplx)) to convert between SMPL-H and SMPL-X using the AMASS sample data. It seems to have worked. My notes are [here](https://github.com/gngdb/smplx/blob/master/transfer_model/DEBUG_NOTES.md#10th-february-2022), including the exact sequence of commands I ran.

If I have time I'll implement a conversion script that doesn't require these multiple steps. Writing the `.obj` files is a trivial step so it seems unnecessary to make the user do it manually.

**Comment by soddday** [comment]
Hi @gngdb I also meet problem when convert SMPLX to SMPLH with .ply meshes.
`(.venv) PS E:\smplx2smplh\smplx> python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\smplx2smplh\smplx\transfer_model\__main__.py", line 30, in <module>
    from .config import parse_args
  File "E:\smplx2smplh\smplx\transfer_model\config\__init__.py", line 17, in <module>
    from .cmd_parser import parse_args
  File "E:\smplx2smplh\smplx\transfer_model\config\cmd_parser.py", line 27, in <module>
    from .defaults import conf as default_conf
  File "E:\smplx2smplh\smplx\transfer_model\config\defaults.py", line 24, in <module>
    from .dataset_defaults import conf as dataset_cfg, DatasetConfig
  File "E:\smplx2smplh\smplx\transfer_model\config\dataset_defaults.py", line 26, in <module>
    @dataclass
     ^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'transfer_model.config.dataset_defaults.MeshFolder'> for field mesh_folder is not allowed: use default_factory
(.venv) PS E:\smplx2smplh\smplx> `

I just run my code to use SMPLX parameters( npz file) to get SMPLX meshes(.ply) because I can't run `python write_obj.py --model-folder ../models/ --motion-file ../transfer_data/support_data/github_data/amass_sample.npz --output-folder ../transfer_data/meshes/amass_sample/` in [readme](https://github.com/vchoutas/smplx/blob/main/transfer_model/README.md). 
But when I use my ply meshes to convert SMPLX to SMPLH by running `python -m transfer_model --exp-cfg config_files/smplx2smplh.yaml` 
I meet error above.
So if I want to use your fork to convert SMPLX to SMPLH  (.ply), what edits should I make???
