### ISSUE TITLE
cannot import name 'ModelOutput' from 'smplx.body_models'

### ISSUE THREAD

**Issue by mahui97** [vchoutas/smplx#96]
I use `pip install smplx[all]` to install smplx，and try to use it in SPIN(https://github.com/nkolot/SPIN), but there is an error.

(base) ubuntu@ubuntu-C246-WU4:~/mahui/SPIN$ python3 demo.py --checkpoint=data/model_checkpoint.pt --img=examples/im1010.jpg --openpose=examples/im1010_openpose.json
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    from models import hmr, SMPL
  File "/home/ubuntu/mahui/SPIN/models/__init__.py", line 2, in <module>
    from .smpl import SMPL
  File "/home/ubuntu/mahui/SPIN/models/smpl.py", line 5, in <module>
    from smplx.body_models import ModelOutput
ImportError: cannot import name 'ModelOutput' from 'smplx.body_models' (/home/ubuntu/anaconda3/lib/python3.7/site-packages/smplx/body_models.py)

**Comment by mayank64ce** [comment]
I am facing the same error. Any solution ?

**Comment by qaz8788817** [comment]
I encountered a problem similar to this one. Could you please advise on how you resolved it?

**Comment by siyuankth** [comment]
Do you have a solution?

**Comment by avasenin-14** [comment]
You can probably change the 5 line in SPIN/models/smpl.py from
'from smplx.body_models import ModelOutput'
to
'from smplx.utils import ModelOutput'.

Though no guarantee there won't be any other errors down the line as it seems that there is no incentive for the authors to maintain the SPIN project.
