### ISSUE TITLE
missing pkl files and smplx exiting ValueErrors

### ISSUE THREAD

**Issue by didrudcks** [vchoutas/smplx#97]
Hi, I'm trying to use smplify-x and on the dependencies, I need to finish smplx first so I started working on it but I faced to this probelm and I have no idea where those pkl files at.
I'm using window 10 and python 3.6.8, I followed the directions.
I install smplx[all] and inside of its file, I ran the command ":git clone https://github.com/vchoutas/smplx
python setup.py install"
then I downloaded some models from the site (I'm not sure if I have to download all or specific ones. I only downloaded SMPL-X Model, VPoser, Homogenus, Mano and Flame, and Model correspondences.)

But when I try the commands from READ.ME files, I get the following errors.

FROM : "python tools/clean_ch.py --input-models path-to-models/*.pkl --output-folder output-folder"

Got :  "Traceback (most recent call last):
File "tools/clean_ch.py", line 68, in <module>
clean_fn(input_model, output_folder=output_folder)
File "tools/clean_ch.py", line 33, in clean_fn
with open(fn, 'rb') as body_file:
FileNotFoundError: [Errno 2] No such file or directory: 'path-to-models/*.pkl'"

FROM : "python tools/merge_smplh_mano.py --smplh-fn SMPLH_FOLDER/SMPLH_GENDER.pkl \
 --mano-left-fn MANO_FOLDER/MANO_LEFT.pkl \
 --mano-right-fn MANO_FOLDER/MANO_RIGHT.pkl \
 --output-folder OUTPUT_FOLDER" 

GOT : "Traceback (most recent call last):
File "tools/merge_smplh_mano.py", line 89, in <module>
merge_models(smplh_fn, mano_left_fn, mano_right_fn, output_folder)
File "tools/merge_smplh_mano.py", line 32, in merge_models
with open(smplh_fn, 'rb') as body_file:
FileNotFoundError: [Errno 2] No such file or directory: 'SMPLH_FOLDER/SMPLH_GENDER.pkl'"

FROM : "python examples/vis_mano_vertices.py --model-folder $SMPLX_FOLDER --corr-fname correspondences/MANO_SMPLX_vertex_ids.pkl"

GOT : "Traceback (most recent call last):
  File "examples/vis_mano_vertices.py", line 98, in <module>
    gender=gender, hand=hand
  File "examples/vis_mano_vertices.py", line 43, in main
    ext=ext)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\smplx\body_models.py", line 2410, in create
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type $smplx, exiting!"

FROM : "python examples/vis_flame_vertices.py --model-folder $SMPLX_FOLDER --corr-fname correspondences/SMPL-X__FLAME_vertex_ids.npy"

GOT : "Traceback (most recent call last):
  File "examples/vis_flame_vertices.py", line 91, in <module>
    gender=gender
  File "examples/vis_flame_vertices.py", line 36, in main
    ext=ext)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\smplx\body_models.py", line 2410, in create
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type $smplx, exiting!"

FROM : "python examples/demo.py --model-folder $SMPLX_FOLDER --plot-joints=True --gender="neutral""

GOT : "Traceback (most recent call last):
File "examples/demo.py", line 180, in <module>
use_face_contour=use_face_contour)
File "examples/demo.py", line 42, in main
ext=ext)
File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\smplx\body_models.py", line 2410, in create
raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type $smplx, exiting!"

I cannot find those pkl files and I have no idea why they say smplx exiting. I even tried after I removed my smplx file, but it gives the same errors

**Comment by shxutoki** [comment]
Do you solve it now?
